site_name: Epic7 Bot
site_description: Project documentation for Epic7 Bot.
site_author: brunocordioli072

repo_url: https://github.com/brunocordioli072/epic7_bot
edit_uri: blob/master/docs/

theme:
    name: mkdocs
    locale: en

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide:
        - User Guide: user-guide/README.md
        - Instalation: user-guide/installation.md
        - Commands: user-guide/commands.md
    # - Developer Guide: dev-guide/
