name: Build and publish release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-on-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .\packages\core\requirements.txt

    - name: Build with pyinstaller
      run: |
        pyinstaller config/windows.spec

    - uses: actions/upload-artifact@v2
      with:
        name: app_windows
        path: .\dist\Epic7 Bot.exe

  create-release:
    runs-on: ubuntu-latest
    needs: [build-on-windows]

    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ./

    - name: Create github release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload windows artifact to github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app_windows/app.exe
        asset_name: app_windows.exe
        asset_content_type: application